//===-- RL78ISelDAGToDAG.cpp - A dag to dag inst selector for RL78 ------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines an instruction selector for the RL78 target.
//
//===----------------------------------------------------------------------===//

#include "RL78TargetMachine.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"

using namespace llvm;

//===----------------------------------------------------------------------===//
// Instruction Selector Implementation
//===----------------------------------------------------------------------===//

//===--------------------------------------------------------------------===//
/// RL78DAGToDAGISel - RL78 specific code to select RL78 machine
/// instructions for SelectionDAG operations.

#define DEBUG_TYPE "rl78-isel"
#define PASS_NAME "RL78 DAG->DAG Pattern Instruction Selection"

namespace {
class RL78DAGToDAGISel : public SelectionDAGISel {
  /// Subtarget - Keep a pointer to the RL78 Subtarget around so that we can
  /// make the right decision when generating code for different targets.
  const RL78Subtarget *Subtarget = nullptr;

  void MatchSET1CLR1(SDNode *&N);
  bool MatchLOAD_SELECTCC(SDNode *&N);
  SDNode *SelectFI(SDNode *N);

public:
  static char ID;

  RL78DAGToDAGISel() = delete;

  explicit RL78DAGToDAGISel(RL78TargetMachine &TargetMachine,
                            CodeGenOpt::Level OptLevel)
      : SelectionDAGISel(ID, TargetMachine, OptLevel) {}

  bool runOnMachineFunction(MachineFunction &MF) override {
    Subtarget = &MF.getSubtarget<RL78Subtarget>();
    return SelectionDAGISel::runOnMachineFunction(MF);
  }

  void PreprocessISelDAG() override;
  void PostprocessISelDAG() override;

  void Select(SDNode *N) override;
  // Complex Pattern Selectors.
  bool SelectADDRr(SDValue Addr, SDValue &Base);
  bool SelectADDRrr(SDValue Addr, SDValue &R1, SDValue &R2);
  bool SelectADDRSPi(SDValue Addr, SDValue &Base, SDValue &Offset);

  template <int Max, bool AllowWordBC = false>
  bool SelectADDRri(SDValue Addr, SDValue &Base, SDValue &Offset) {
    return SelectADDRri(Addr, Max, AllowWordBC, Base, Offset);
  }
  bool SelectADDRri(SDValue Addr, unsigned Size, bool AllowWordBC, SDValue &Base,
                    SDValue &Offset, bool PermitFrameIndex = false);
  bool SelectADDRr8i16(SDValue Addr, SDValue &Base,
                    SDValue &Offset);

  bool SelectADDRABS16(SDValue Addr, SDValue &Base);
  bool SelectSaddr(SDValue Addr, SDValue &Base);
  bool SelectSFR(SDValue Addr, SDValue &Base);

  bool SelectESADDRr(SDValue Addr, SDValue &BaseHi, SDValue &BaseLow);
  bool SelectESADDRrr(SDValue Addr,  SDValue &BaseHi, SDValue &R1, SDValue &R2);
  template <int Max, bool AllowWordBC = false>
  bool SelectESADDRri(SDValue Addr, SDValue &BaseHi, SDValue &BaseLow, SDValue &Offset) {
    return SelectESADDRri(Addr, Max, AllowWordBC, BaseHi, BaseLow, Offset);
  }
  bool SelectESADDRri(SDValue Addr, unsigned Size, bool AllowWordBC, SDValue &BaseHi, SDValue &BaseLow,
                    SDValue &Offset);
  bool SelectESADDRr8i16(SDValue Addr, SDValue &BaseHi, SDValue &BaseLow,
                    SDValue &Offset);
  bool SelectESADDRABS16(SDValue Addr, SDValue &BaseHi, SDValue &BaseLow);

  StringRef getPassName() const override {
    return "RL78 DAG->DAG Pattern Instruction Selection";
  }

  // Include the pieces autogenerated from the target description.
#include "RL78GenDAGISel.inc"
};
} // end anonymous namespace

static SDValue TraversePossibleMOV(SDValue Value) {
  if (Value.isMachineOpcode() &&
      (Value.getMachineOpcode() == RL78::MOV_r_imm ||
       Value.getMachineOpcode() == RL78::MOVW_rp_imm))
    return Value.getOperand(0);
  return Value;
}

static bool AreCmpOpsEqual(SDValue Cmp) {
  // Avoid matching cmp_r_memri  t41, t41, ...
  // see gcc.c_torture\pr33870.c -O1
  if (Cmp.getMachineOpcode() != RL78::CMPW_rp_imm &&
      Cmp.getMachineOpcode() != RL78::CMPW_rp_rp &&
      Cmp.getMachineOpcode() != RL78::CMP_r_imm &&
      Cmp.getMachineOpcode() != RL78::CMP_r_r)
    return false;

  SDValue LHS = Cmp.getOperand(0);
  SDValue RHS = Cmp.getOperand(1);
  return TraversePossibleMOV(LHS) == TraversePossibleMOV(RHS);
}

void RL78DAGToDAGISel::PreprocessISelDAG() {
  SelectionDAG::allnodes_iterator Position = CurDAG->allnodes_end();

  bool MadeChange = false;
  while (Position != CurDAG->allnodes_begin()) {
    SDNode *N = &*--Position;
    // Skip dead nodes.
    if (N->use_empty())
      continue;

    switch (N->getOpcode()) {
    default:
      break;
    case ISD::LOAD:
      MadeChange |= MatchLOAD_SELECTCC(N);
      break;
    }
  }
  if (MadeChange)
    CurDAG->RemoveDeadNodes();
}

void RL78DAGToDAGISel::PostprocessISelDAG() {
  SelectionDAG::allnodes_iterator Position = CurDAG->allnodes_end();

  bool MadeChange = false;
  while (Position != CurDAG->allnodes_begin()) {
    SDNode *N = &*--Position;
    // Skip dead nodes and any non-machine opcodes.
    if (N->use_empty() || !N->isMachineOpcode())
      continue;

    // Eliminate cmp(w) ax, ax
    //           selectcc ...
    // Assume that N->getOperand(3).getMachineOpcode() == CMP_*.
    if (((N->getMachineOpcode() == RL78::SELECTCC16_rp_rp ||
         N->getMachineOpcode() == RL78::SELECTCC16_imm_rp ||
         N->getMachineOpcode() == RL78::SELECTCC16_rp_imm ||
         N->getMachineOpcode() == RL78::SELECTCC16_imm_imm ||
         N->getMachineOpcode() == RL78::SELECTCC8_r_r ||
         N->getMachineOpcode() == RL78::SELECTCC8_imm_r) &&
            AreCmpOpsEqual(N->getOperand(3))) ||
        ((N->getMachineOpcode() == RL78::SELECTCC16_esaddr_rp ||
         N->getMachineOpcode() == RL78::SELECTCC16_esaddr_imm ||
         N->getMachineOpcode() == RL78::SELECTCC8_esaddr_r ||
         N->getMachineOpcode() == RL78::SELECTCC8_esaddr_imm) &&
            AreCmpOpsEqual(N->getOperand(5)))) {

      SDValue SelectionResult;
      SDValue TrueValue = N->getOperand(0);
      SDValue FalseValue = N->getOperand(1);
      switch ((RL78CC::CondCodes)N->getConstantOperandVal(2)) {
      case RL78CC::RL78CC_C:
      case RL78CC::RL78CC_NZ:
      case RL78CC::RL78CC_H:
        SelectionResult = FalseValue;
        break;
      case RL78CC::RL78CC_NC:
      case RL78CC::RL78CC_NH:
      case RL78CC::RL78CC_Z:
        SelectionResult = TrueValue;
        break;
      }

      CurDAG->ReplaceAllUsesWith(N, &SelectionResult);
      MadeChange = true;
    } else if (N->getMachineOpcode() == RL78::BRCC &&
               AreCmpOpsEqual(N->getOperand(3))) {
      // see gcc.c_torture\scal-to-vec1.c. -O3
      switch ((RL78CC::CondCodes)N->getConstantOperandVal(1)) {
      case RL78CC::RL78CC_C:
      case RL78CC::RL78CC_NZ:
      case RL78CC::RL78CC_H: {
        auto tgtBB = (BasicBlockSDNode *)N->getOperand(0).getNode();
        if (tgtBB->hasOneUse())
          FuncInfo.get()->MBB->removeSuccessor(tgtBB->getBasicBlock(), true);
        CurDAG->ReplaceAllUsesWith(N, &N->getOperand(2));
      } break;
      case RL78CC::RL78CC_NC:
      case RL78CC::RL78CC_NH:
      case RL78CC::RL78CC_Z: {
        SDLoc dl(N);
        MachineSDNode *BranchNode =
            CurDAG->getMachineNode(RL78::BR, dl, N->getValueType(0),
                                   N->getOperand(0), N->getOperand(2));
        CurDAG->ReplaceAllUsesWith(N, BranchNode);
        // Also nullify the fall-through BR, now unreachable.
        for (auto Use : BranchNode->uses()) {
          if (Use->getMachineOpcode() == RL78::BR) {
            auto tgtBB = (BasicBlockSDNode *)Use->getOperand(0).getNode();
            if (tgtBB->hasOneUse())
              FuncInfo.get()->MBB->removeSuccessor(tgtBB->getBasicBlock(), true);
            CurDAG->ReplaceAllUsesWith(Use, &Use->getOperand(1));
            break;
          }
        }
      } break;
      }
      MadeChange = true;
    } else if ((N->getMachineOpcode() ==
                    RL78::LOAD_SELECTCC8_r_esaddr16_esaddr16 ||
                N->getMachineOpcode() ==
                    RL78::LOAD_SELECTCC16_rp_esaddr16_esaddr16 ||
                N->getMachineOpcode() ==
                    RL78::LOAD_SELECTCC8_r_esaddrr_esaddrr ||
                N->getMachineOpcode() ==
                    RL78::LOAD_SELECTCC16_rp_esaddrr_esaddrr) &&
               AreCmpOpsEqual(N->getOperand(6))) {
      SDValue AddrHi, AddrLo;
      switch ((RL78CC::CondCodes)N->getConstantOperandVal(4)) {
      case RL78CC::RL78CC_C:
      case RL78CC::RL78CC_NZ:
      case RL78CC::RL78CC_H:
        AddrHi = N->getOperand(2);
        AddrLo = N->getOperand(3);
        break;
      case RL78CC::RL78CC_NC:
      case RL78CC::RL78CC_NH:
      case RL78CC::RL78CC_Z:
        AddrHi = N->getOperand(0);
        AddrLo = N->getOperand(1);
        break;
      }

      llvm::SmallVector<SDValue, 4> Ops = { AddrHi, AddrLo };
      unsigned LdOpcode;
      SDLoc dl(N);

      switch (N->getMachineOpcode()) {
      default:
        llvm_unreachable("Unknown opcode.");
      case RL78::LOAD_SELECTCC8_r_esaddr16_esaddr16:
        LdOpcode = RL78::MOV_r_esaddr16;
        break;
      case RL78::LOAD_SELECTCC16_rp_esaddr16_esaddr16:
        LdOpcode = RL78::LOAD16_rp_esaddr16;
        break;
      case RL78::LOAD_SELECTCC8_r_esaddrr_esaddrr:
        LdOpcode = RL78::LOAD8_r_esrpi;
        Ops.push_back(CurDAG->getTargetConstant(0, dl, MVT::i16)); // +0 offset (imm).
        break;
      case RL78::LOAD_SELECTCC16_rp_esaddrr_esaddrr:
        LdOpcode = RL78::LOAD16_rp_esrpi;
        Ops.push_back(CurDAG->getTargetConstant(0, dl, MVT::i16)); // +0 offset (imm).
        break;
      }

      MachineSDNode *LdNode = CurDAG->getMachineNode(LdOpcode, dl, N->getValueType(0), Ops);
      CurDAG->ReplaceAllUsesWith(N, LdNode);
      MadeChange = true;
    }
  }
  if (MadeChange)
    CurDAG->RemoveDeadNodes();
}

bool RL78DAGToDAGISel::SelectADDRSPi(SDValue Addr, SDValue &Base,
                                     SDValue &Offset) {
  // Addr.dump(CurDAG);
  if (FrameIndexSDNode *FIN = dyn_cast<FrameIndexSDNode>(Addr)) {
    Base = CurDAG->getTargetFrameIndex(
        FIN->getIndex(), TLI->getPointerTy(CurDAG->getDataLayout()));
    Offset = CurDAG->getTargetConstant(0, SDLoc(Addr), MVT::i16);
    return true;
  }
  if (Addr.getOpcode() == ISD::ADD || Addr.getOpcode() == ISD::OR) {
    if (ConstantSDNode *CN = dyn_cast<ConstantSDNode>(Addr.getOperand(1))) {
      if (isUInt<16>(CN->getZExtValue())) {
        if (FrameIndexSDNode *FIN =
                dyn_cast<FrameIndexSDNode>(Addr.getOperand(0))) {
          // Constant offset from frame ref.
          Base = CurDAG->getTargetFrameIndex(
              FIN->getIndex(), TLI->getPointerTy(CurDAG->getDataLayout()));
          Offset = CurDAG->getTargetConstant(CN->getZExtValue(), SDLoc(Addr),
                                             MVT::i16);
          return true;
        }
      }
    }
  }
  return false;
}

bool RL78DAGToDAGISel::SelectADDRr(SDValue Addr, SDValue &Base) {
  if (Addr.getOpcode() == RL78ISD::LOW16 ||
      (Addr.getOpcode() == ISD::ADD &&
       Addr->getOperand(0).getOpcode() == RL78ISD::HI16))
    return false;
  if (Addr.getOpcode() == RL78ISD::HI16)
    return false;
  if (Addr.getOpcode() == RL78ISD::LOW8)
    return false;
  if (Addr.getOpcode() == ISD::FrameIndex)
    return false;
  if (Addr.getOpcode() == ISD::Constant)
    return false;
  if (Addr.getOpcode() == ISD::TargetExternalSymbol ||
      Addr.getOpcode() == ISD::TargetGlobalAddress ||
      Addr.getOpcode() == ISD::TargetBlockAddress)
    return false; // Direct calls.
  Base = Addr;
  return true;
}

bool RL78DAGToDAGISel::SelectADDRri(SDValue Addr, unsigned Max, bool AllowWordBC, SDValue &Base,
                                    SDValue &Offset, bool PermitFrameIndex) {
  // Addr.dump(CurDAG);
  if (Addr.getOpcode() == RL78ISD::LOW16)
    return false;
  if (Addr.getOpcode() == RL78ISD::HI16)
    return false;
  if (Addr.getOpcode() == RL78ISD::LOW8)
    return false;
  if (!PermitFrameIndex && Addr.getOpcode() == ISD::FrameIndex)
    return false;
  if (Addr.getOpcode() == ISD::Constant)
    return false;
  if (Addr.getOpcode() == ISD::TargetExternalSymbol ||
      Addr.getOpcode() == ISD::TargetGlobalAddress ||
      Addr.getOpcode() == ISD::TargetBlockAddress)
    return false; // Direct calls.

  if (Addr.getOpcode() == ISD::ADD || Addr.getOpcode() == ISD::OR) {
    if (ConstantSDNode *CN = dyn_cast<ConstantSDNode>(Addr.getOperand(1))) {
      if (!PermitFrameIndex &&
          dyn_cast<FrameIndexSDNode>(Addr.getOperand(0)) != nullptr) {
        return false;
      }
      if(Addr.getOperand(0).getOpcode() ==  RL78ISD::LOW16)
          return false;
      if ((CN->getSExtValue() > 0) && (CN->getSExtValue() <= Max)) {
        Base = Addr.getOperand(0);
        Offset = CurDAG->getTargetConstant(CN->getZExtValue(), SDLoc(Addr),
                                           MVT::i16);
        return true;
      }
    } else if (AllowWordBC && Addr.getOperand(1).getOpcode() == RL78ISD::LOW16) {
      Base =  Addr.getOperand(0);
      Offset = Addr.getOperand(1).getOperand(0);
      return true;
    }
  }
  Base = Addr;
  Offset = CurDAG->getTargetConstant(0, SDLoc(Addr), MVT::i16);
  return true;
}

bool RL78DAGToDAGISel::SelectADDRrr(SDValue Addr, SDValue &R1, SDValue &R2) {
  if (Addr.getOpcode() == RL78ISD::LOW16)
    return false;
  if (Addr.getOpcode() == RL78ISD::HI16)
    return false;
  if (Addr.getOpcode() == RL78ISD::LOW8)
    return false;
  if (Addr.getOpcode() == ISD::FrameIndex)
    return false;
  if (Addr.getOpcode() == ISD::TargetExternalSymbol ||
      Addr.getOpcode() == ISD::TargetGlobalAddress ||
      Addr.getOpcode() == ISD::TargetBlockAddress)
    return false; // direct calls.

  if (Addr.getOpcode() == ISD::ADD) {
    if (ConstantSDNode *CN = dyn_cast<ConstantSDNode>(Addr.getOperand(1)))
      return false;
    // the index must be zero-extended to i16 (full 16-bit index is not supported,
    // also sign-extension won't work for negative values)
    if ((Addr.getValueType() != MVT::i16) ||
        (Addr.getOperand(1).getOpcode() != ISD::ZERO_EXTEND))
      return false;
    R1 = Addr.getOperand(0);
    R2 = Addr.getOperand(1)->getOperand(0);
    return true;
  }
  //
  return false;
}

static bool selectADDRABS16(SDValue Addr, SDValue &Base, SelectionDAG *CurDAG,
                            bool checkSFR) {
  if (Addr.getOpcode() == RL78ISD::LOW16 &&
      (Addr.getOperand(0).getOpcode() == ISD::TargetGlobalAddress ||
       Addr.getOperand(0).getOpcode() == ISD::Constant)) {
    Base = Addr->getOperand(0);
    return true;
  }

  // addr16 + const
  if (Addr.getOpcode() == ISD::ADD &&
      ((Addr.getOperand(0).getOpcode() == ISD::Constant &&
           Addr.getOperand(1).getOpcode() == RL78ISD::LOW16) ||
       (Addr.getOperand(1).getOpcode() == ISD::Constant &&
           Addr.getOperand(0).getOpcode() == RL78ISD::LOW16))) {

    int64_t additionalOffset = 0;
    SDValue Low16;
    if (Addr.getOperand(0).getOpcode() == ISD::Constant) {
      additionalOffset = Addr.getConstantOperandVal(0);
      Low16 = Addr.getOperand(1);
    } else {
      additionalOffset = Addr.getConstantOperandVal(1);
      Low16 = Addr.getOperand(0);
    }

    if (Low16.getOperand(0).getOpcode() == ISD::TargetGlobalAddress) {
      GlobalAddressSDNode *globalAddress = dyn_cast<GlobalAddressSDNode>(Low16.getOperand(0));
      int64_t originalOffset = globalAddress->getOffset();
      Base = CurDAG->getTargetGlobalAddress(
          globalAddress->getGlobal(), SDLoc(Low16.getOperand(0)), MVT::i16,
          originalOffset + additionalOffset, globalAddress->getTargetFlags());
      return true;
    } else if (Low16.getOperand(0).getOpcode() == ISD::Constant) {
      uint64_t address =
          dyn_cast<ConstantSDNode>(Low16.getOperand(0))->getConstantIntValue()->getZExtValue();
      Base = CurDAG->getTargetConstant(address + additionalOffset, SDLoc(Low16.getOperand(0)),
                                       MVT::i16);
      return true;
    } else {
      return false;
    }
  }

  if (Addr.getOpcode() == ISD::Constant) {
    unsigned address =
        dyn_cast<ConstantSDNode>(Addr)->getConstantIntValue()->getZExtValue();
    if (checkSFR && (address >= 0xFF00))
      return false;
    Base = CurDAG->getTargetConstant(address, SDLoc(Addr), MVT::i16);
    return true;
  }

  return false;
}

bool RL78DAGToDAGISel::SelectADDRABS16(SDValue Addr, SDValue &Base) {
  return selectADDRABS16(Addr, Base, CurDAG, true);
}

bool RL78DAGToDAGISel::SelectADDRr8i16(SDValue Addr, SDValue &Base,
                                       SDValue &Offset) {
  if (Addr.getOpcode() !=  ISD::ADD ||
      Addr.getValueType() != MVT::i16)
    return false;

  if (selectADDRABS16(Addr.getOperand(0), Offset, CurDAG, false) &&
      Addr.getOperand(1).getOpcode() == ISD::ZERO_EXTEND)
    Base = Addr.getOperand(1).getOperand(0);
  else if (selectADDRABS16(Addr.getOperand(1), Offset, CurDAG, false) &&
           Addr.getOperand(0).getOpcode() == ISD::ZERO_EXTEND)
    Base = Addr.getOperand(0).getOperand(0);
  else
    return false;
  return Base.getValueType() == MVT::i8;
}

static bool SelectBaseHi(SDValue Addr, SDValue &BaseHi, SelectionDAG *CurDAG) {
  if (Addr.getOpcode() != RL78ISD::HI16)
    return false;
  if (Addr.getOperand(0).getOpcode() == ISD::Constant)
    BaseHi = CurDAG->getTargetConstant(Addr.getConstantOperandVal(0),
                                       SDLoc(Addr), MVT::i16);
  else
    BaseHi = Addr.getOperand(0);
  return true;
}

bool RL78DAGToDAGISel::SelectESADDRr(SDValue Addr, SDValue &BaseHi,
                                     SDValue &BaseLow) {
  return SelectBaseHi(Addr, BaseHi, CurDAG) &&
         SelectADDRr(Addr.getOperand(1), BaseLow);
}

bool RL78DAGToDAGISel::SelectESADDRrr(SDValue Addr, SDValue &BaseHi, SDValue &R1, SDValue &R2) {
    return SelectBaseHi(Addr, BaseHi, CurDAG) &&
         SelectADDRrr(Addr.getOperand(1), R1, R2);
}

bool RL78DAGToDAGISel::SelectESADDRri(SDValue Addr, unsigned Size,
                                      bool AllowWordBC, SDValue &BaseHi,
                                      SDValue &BaseLow, SDValue &Offset) {
  return SelectBaseHi(Addr, BaseHi, CurDAG) &&
         SelectADDRri(Addr.getOperand(1), Size, AllowWordBC, BaseLow, Offset, true);
}

bool RL78DAGToDAGISel::SelectESADDRr8i16(SDValue Addr, SDValue &BaseHi, SDValue &BaseLow,
                       SDValue &Offset) {
    return SelectBaseHi(Addr, BaseHi, CurDAG) &&
         SelectADDRr8i16(Addr.getOperand(1), BaseLow, Offset);
}

bool RL78DAGToDAGISel::SelectESADDRABS16(SDValue Addr, SDValue &BaseHi,
                                         SDValue &BaseLow) {
  return SelectBaseHi(Addr, BaseHi, CurDAG) &&
         selectADDRABS16(Addr.getOperand(1), BaseLow, CurDAG, false);
}

bool RL78DAGToDAGISel::SelectSaddr(SDValue Addr, SDValue &Base) {
  if (Addr.getOpcode() != RL78ISD::LOW8)
    return false;
  Base = Addr->getOperand(0);
  return true;
}

bool RL78DAGToDAGISel::SelectSFR(SDValue Addr, SDValue &Base) {
  if (Addr.getOpcode() != ISD::Constant)
    return false;
  unsigned address =
      dyn_cast<ConstantSDNode>(Addr)->getConstantIntValue()->getZExtValue();
  if (address < 0xFF00)
    return false;
  Base = CurDAG->getTargetConstant(address, SDLoc(Addr), MVT::i16);
  return true;
}

// HARD REQUIREMENT:
// 11.1.8 Controlling the Output of Bit Manipulation Instructions [V1.04 or
// later] To output bit manipulation instructions without using intrinsic
// functions, satisfy all conditions shown below. (a) A constant value is
// assigned. (b) The value is assigned to a single-bit bit field of the
// charunsigned charsigned char_Bool type in the near area. (c) The bit field
// where the value is assigned is qualified with volatile.
void RL78DAGToDAGISel::MatchSET1CLR1(SDNode *&N) {
  //   LOAD  IMM
  //    \     /
  //     \   /
  //     AND/OR
  //       |
  //     STORE
  const SDValue &logicalOp = N->getOperand(1);
  if ((logicalOp->getOpcode() != ISD::AND) &&
      (logicalOp->getOpcode() != ISD::OR))
    return;
  EVT VT = logicalOp->getValueType(0);
  if ((VT != MVT::i8) && (VT != MVT::i16))
    return;
  // The logical op needs to have only one use.
  if (!logicalOp->hasOneUse())
    return;
  const SDValue &load = logicalOp->getOperand(0);

  if ((load->getOpcode() != ISD::LOAD))
    return;
  // Reducing the width of a volatile load is illegal.
  if (VT == MVT::i16) {
    LoadSDNode *LN = cast<LoadSDNode>(load);
    if (LN->isVolatile())
      return;
  }

  // Check the chain uses for the load instruction:
  // the store is the only user either directly or through
  // a TokenFactor.
  SDNode *chainNode = nullptr;
  SDNode::use_iterator UI = load.getNode()->use_begin(),
                       UE = load.getNode()->use_end();
  while (UI != UE) {
    SDUse &Use = UI.getUse();
    if (Use.getResNo() == 1 && Use.getUser() != N) {
      if (Use.getUser()->getOpcode() == ISD::TokenFactor) {
        if ((!Use.getUser()->hasOneUse()) ||
            (Use.getUser()->use_begin().getUse().getUser() != N))
          return;
        else
          chainNode = Use.getUser();
      } else
        return;
    } else if (Use.getResNo() == 0 && Use.getUser() != logicalOp.getNode())
      return;
    ++UI;
  }
  const SDValue &chain =
      chainNode ? SDValue(chainNode, 0) : load->getOperand(0);

  // The load and store need to use the same address.
  if (load->getOperand(1) != N->getOperand(2))
    return;
  // Check the constant node is power of 2.
  if (!isa<ConstantSDNode>(logicalOp->getOperand(1)))
    return;
  uint64_t imm = logicalOp->getConstantOperandVal(1);
  if (logicalOp->getOpcode() == ISD::AND)
    imm = ~imm & ((VT == MVT::i8) ? 0xFF : 0xFFFF);
  if (!isPowerOf2_64(imm))
    return;
  // Make sure we can select.
  SDValue memOp = N->getOperand(2);
  if (FrameIndexSDNode *FIN = dyn_cast<FrameIndexSDNode>(memOp)) {
    SDNode *MFIN = SelectFI(FIN);
    memOp = SDValue(MFIN, 0);
  }
  if (VT == MVT::i16) {
    if (imm & 0xFF00) {
      imm = imm >> 8;
      SDLoc dl(N);
      SDValue one = CurDAG->getConstant(1, dl, MVT::i16);
      SDNode *newMemOpNode =
          CurDAG->getMachineNode(RL78::ADDW_rp_imm, dl, MVT::i16, memOp, one);
      SDValue memOp(newMemOpNode, 0);
    }
    VT = MVT::i8;
  }
  SDLoc dl(N);
  SDValue constVal = CurDAG->getConstant(Log2_64(imm), dl, VT);
  RL78ISD::NodeType opcode =
      (logicalOp->getOpcode() == ISD::AND) ? RL78ISD::CLR1 : RL78ISD::SET1;
  SDValue set1 = CurDAG->getNode(
      opcode, dl, MVT::Other, chain, constVal, memOp);
  // Update DAG.
  CurDAG->ReplaceAllUsesWith(N, &set1);
  CurDAG->RemoveDeadNodes();
  N = set1.getNode();
  return;
}

// Replace loads from SELECTCC between far addresses with LOAD_SELECTCC.
// Needed for allowing the optimization from DAGCombiner::SimplifySelectOps()
// when -mfar-data (i.e. the ptrs in the default address space are far), as
// otherwise the load generates incorrect code (a near-address load from the
// HI16 part of the selected far address). Returns true on success.
bool RL78DAGToDAGISel::MatchLOAD_SELECTCC(SDNode*& N) {
  LoadSDNode *LD = cast<LoadSDNode>(N);
  SDValue Ptr = LD->getBasePtr();

  if (LD->isSimple() && Ptr.getOpcode() == RL78ISD::SELECTCC) {
    SDValue TrueAddr = Ptr.getOperand(0);
    SDValue FalseAddr = Ptr.getOperand(1);

    if (TrueAddr.getOpcode() == RL78ISD::HI16 || FalseAddr.getOpcode() == RL78ISD::HI16) {
      SDValue Chain = LD->getChain();
      SDValue TargetCC = Ptr.getOperand(2);
      SDValue Cmp = Ptr.getOperand(3);

      // Result type list: (valueVT, chain).
      SDVTList VTs = CurDAG->getVTList(N->getValueType(0), MVT::Other);

      // Build operands with incoming chain first, glue last.
      SDValue Ops[] = { Chain, TrueAddr, FalseAddr, TargetCC, Cmp };
      SDValue LoadSelectCC = CurDAG->getNode(RL78ISD::LOAD_SELECTCC, SDLoc(N), VTs, Ops);
      CurDAG->ReplaceAllUsesWith(N, LoadSelectCC.getNode());
      N = LoadSelectCC.getNode();
      return true;
    }
  }
  return false;
}

SDNode *RL78DAGToDAGISel::SelectFI(SDNode *N) {
  SDLoc DL(N);
  // N->dump();
  int FI = cast<FrameIndexSDNode>(N)->getIndex();
  EVT VT = N->getValueType(0);
  SDValue TFI = CurDAG->getTargetFrameIndex(FI, VT);
  // CurDAG->dump();
  unsigned Opc = RL78::MOVW_rp_stack_slot;
  SDValue Imm = CurDAG->getTargetConstant(0, DL, MVT::i16);
  if (N->hasOneUse()) {
    return CurDAG->SelectNodeTo(N, Opc, VT, TFI, Imm);
  } else {
    SDNode *MN = CurDAG->getMachineNode(Opc, DL, VT, TFI, Imm);
    ReplaceNode(N, MN);
    return MN;
  }
  // CurDAG->dump();
}

void RL78DAGToDAGISel::Select(SDNode *N) {
  SDLoc dl(N);
  if (N->isMachineOpcode()) {
    N->setNodeId(-1);
    return; // Already selected.
  }
  // N->dump(CurDAG);
  switch (N->getOpcode()) {
  default:
    break;
  case ISD::STORE:
    MatchSET1CLR1(N);
    break;
  case ISD::FrameIndex: {
    SelectFI(N);
    return;
  }
  case ISD::TRUNCATE: {
    // In case of right shift + trunc we can remove the shift.
    if ((N->getOperand(0)->getValueType(0) == MVT::i16) &&
        ((N->getOperand(0).getOpcode() == ISD::SRL) ||
        (N->getOperand(0).getOpcode() == ISD::SRA)) &&
        dyn_cast<ConstantSDNode>(N->getOperand(0).getOperand(1)) &&
        N->getOperand(0).getConstantOperandVal(1) == 8) {
      SDValue SubRegHi = CurDAG->getTargetConstant(RL78::sub_hi, dl, MVT::i8);
      SDNode *Hi = CurDAG->getMachineNode(TargetOpcode::EXTRACT_SUBREG, dl,
                                          MVT::i8,
                                 N->getOperand(0)->getOperand(0), SubRegHi);
      ReplaceNode(N, Hi);
      return;
    }
  } break;
  case ISD::SHL: {
    // SHLW AX, 1 is 2 bytes, we can replace it with ADDW AX, AX (1 byte)
    if (N->getOperand(1).getOpcode() == ISD::Constant &&
        N->getConstantOperandVal(1) == 1 && N->getValueType(0) == MVT::i16) {
      SDLoc DL(N);
      EVT VT = MVT::i16;
      unsigned Opc = RL78::ADDW_rp_rp;
      SDNode *MN = CurDAG->getMachineNode(Opc, DL, VT, N->getOperand(0),
                                          N->getOperand(0));
      ReplaceNode(N, MN);
      return;
    }
    break;
  }
  case ISD::BUILD_PAIR: {
    SDLoc DL(N);
    if (N->getValueType(0) == MVT::i16) {
      SDValue RC, SubReg0, SubReg1;
      RC = CurDAG->getTargetConstant(RL78::RL78RPRegsRegClassID, DL, MVT::i16);
      SubReg0 = CurDAG->getTargetConstant(RL78::sub_lo, DL, MVT::i16);
      SubReg1 = CurDAG->getTargetConstant(RL78::sub_hi, DL, MVT::i16);
      const SDValue Ops[] = {RC, N->getOperand(0), SubReg0, N->getOperand(1),
                             SubReg1};
      ReplaceNode(N, CurDAG->getMachineNode(TargetOpcode::REG_SEQUENCE, DL,
                                            N->getValueType(0), Ops));
      return;
    } else {
      llvm_unreachable("Unhandled value type for BUILD_PAIR");
    }
    break;
  }
  }
  // N->dump(CurDAG);
  SelectCode(N);
}

/// createRL78ISelDag - This pass converts a legalized DAG into a
/// RL78-specific DAG, ready for instruction scheduling.
///
FunctionPass *llvm::createRL78ISelDag(RL78TargetMachine &TM,
                                       CodeGenOpt::Level OptLevel) {
  return new RL78DAGToDAGISel(TM, OptLevel);
}

char RL78DAGToDAGISel::ID = 0;

INITIALIZE_PASS(RL78DAGToDAGISel, DEBUG_TYPE, PASS_NAME, false, false)
